In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from catboost import  CatBoostClassifier
from sklearn.preprocessing import  StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, f1_score
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from imblearn.under_sampling import OneSidedSelection, TomekLinks
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE, ADASYN, BorderlineSMOTE
from imblearn.combine import SMOTETomek, SMOTEENN

from lightgbm import LGBMClassifier
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import VotingClassifier
from pycaret.classification import *

In [4]:
# 데이터 불러오기
train = pd.read_csv('./smhrd_data/Train.csv', index_col = 'ID')
test = pd.read_csv('./smhrd_data/test.csv', index_col = 'ID')

# ?를 널값으로 변환
train_df = train.replace('?', pd.NA)
test_df = test.replace('?', pd.NA)

# Gender 컬럼 삭제
train_df.drop('Gender', axis = 1, inplace = True)
test_df.drop('Gender', axis = 1, inplace = True)

# 이상치 제거
train_df = train_df[(train_df['Customer_rating']!=99) & (train_df['Cost_of_the_Product']!=9999)]

# 이상치 변경
test_df['Customer_rating'] = test_df['Customer_rating'].replace(99, 3.0)
test_df['Cost_of_the_Product'] = test_df['Cost_of_the_Product'].replace(9999, 213)

# Product_importance 오타 수정
train_df['Product_importance'] = train_df['Product_importance'].str.replace('mediumm', 'medium')
train_df['Product_importance'] = train_df['Product_importance'].str.replace('loww', 'low')
train_df['Product_importance'] = train_df['Product_importance'].str.replace('highh', 'high')

test_df['Product_importance'] = test_df['Product_importance'].str.replace('mediumm', 'medium')

# Mode_of_Shipment 오타 수정
train_df['Mode_of_Shipment'] = train_df['Mode_of_Shipment'].str.replace('Shipzk', 'Ship')
train_df['Mode_of_Shipment'] = train_df['Mode_of_Shipment'].str.replace('Flightzk', 'Flight')
train_df['Mode_of_Shipment'] = train_df['Mode_of_Shipment'].str.replace('Roadzk', 'Road')

test_df['Mode_of_Shipment'] = test_df['Mode_of_Shipment'].str.replace('Shipzk', 'Ship')
test_df['Mode_of_Shipment'] = test_df['Mode_of_Shipment'].str.replace('Roadzk', 'Road')

# Weight_in_gms 컬럼 int형 변환을 위해 널값을 '0'으로 변환
train_df['Weight_in_gms'] = train_df['Weight_in_gms'].fillna('0')
train_df['Weight_in_gms'] = train_df['Weight_in_gms'].astype('int64')

test_df['Weight_in_gms'] = test_df['Weight_in_gms'].fillna('0')
test_df['Weight_in_gms'] = test_df['Weight_in_gms'].astype('int64')

# Weight_in_gms 결측치 평균값으로 대체
train_df['Weight_in_gms'] = train_df['Weight_in_gms'].replace(0, 3424)
test_df['Weight_in_gms'] = test_df['Weight_in_gms'].replace(0, 3424)

# Discounted_offerd 결측치 평균값으로 채우기
train_df['Discount_offered'] = train_df['Discount_offered'].fillna(13.0)
test_df['Discount_offered'] = test_df['Discount_offered'].fillna(13.0)

# Mode_of_Shipment 결측치 최빈값으로 대체
train_df['Mode_of_Shipment'] = train_df['Mode_of_Shipment'].fillna('Ship')
test_df['Mode_of_Shipment'] = test_df['Mode_of_Shipment'].fillna('Ship')

# Prior_purchases 결측치 평균값으로 대체
train_df['Prior_purchases'] = train_df['Prior_purchases'].fillna(3.5)
test_df['Prior_purchases'] = test_df['Prior_purchases'].fillna(3.5)

# Customer_care_calls 결측치 최빈값이자 평균, 중위값으로 대체
train_df['Customer_care_calls'] = train_df['Customer_care_calls'].fillna(4.0)
test_df['Customer_care_calls'] = test_df['Customer_care_calls'].fillna(4.0)

# Product_importance 최빈값으로 대체
train_df['Product_importance'].fillna('low', inplace = True)
test_df['Product_importance'].fillna('low', inplace = True)

# 라벨 인코딩
from sklearn.preprocessing import LabelEncoder
object_columns = train_df.select_dtypes('object').columns

for i in object_columns:

    lb = LabelEncoder()
    lb.fit(train_df[i])
    train_df[i] = lb.transform(train_df[i])
    
    print(f'category : {np.unique(train_df[i])}\nclasses : {lb.classes_}\n')

for i in object_columns:

    lb = LabelEncoder()
    lb.fit(test_df[i])
    test_df[i] = lb.transform(test_df[i])
    
    print(f'category : {np.unique(test_df[i])}\nclasses : {lb.classes_}\n')
    
# ship 공백 제거
train_df['Mode_of_Shipment'] = train_df['Mode_of_Shipment'].replace(3, 2)
test_df['Mode_of_Shipment'] = test_df['Mode_of_Shipment'].replace(3, 2)

X_train = train_df.drop('Reached.on.Time_Y.N', axis = 1)    
y_train = train_df['Reached.on.Time_Y.N']    
X_test = test_df

category : [0 1 2 3 4]
classes : ['A' 'B' 'C' 'D' 'F']

category : [0 1 2 3]
classes : [' Flight' ' Road' ' Ship' 'Ship']

category : [0 1 2]
classes : ['high' 'low' 'medium']

category : [0 1 2 3 4]
classes : ['A' 'B' 'C' 'D' 'F']

category : [0 1 2 3]
classes : [' Flight' ' Road' ' Ship' 'Ship']

category : [0 1 2]
classes : ['high' 'low' 'medium']

In [5]:
exp_clf = setup(data = X_train, target = y_train, session_id=123, normalize_method='minmax', 
                categorical_features=['Warehouse_block ', 'Mode_of_Shipment', 'Product_importance'])
# 65.61
best_model = compare_models()

In [7]:
# 방법 1
catboost = create_model('catboost')
tuned_catboost = tune_model(catboost, search_library='optuna', optimize='f1' )
gbc = create_model('gbc')
tuned_gbc = tune_model(gbc, search_library='optuna' , optimize='f1')
lightgbm = create_model('lightgbm')
tuned_lightgbm = tune_model(lightgbm, search_library='optuna', optimize='f1' )
rf = create_model('rf')
tuned_rf = tune_model(rf, search_library='optuna' , optimize='f1')

[I 2023-08-10 12:33:05,857] Searching the best hyperparameters using 4895 samples...
[I 2023-08-10 12:34:33,308] Finished hyperparemeter search!

[I 2023-08-10 12:35:21,466] Searching the best hyperparameters using 4895 samples...
[I 2023-08-10 12:37:47,552] Finished hyperparemeter search!

[I 2023-08-10 12:38:33,525] Searching the best hyperparameters using 4895 samples...
[I 2023-08-10 12:40:18,584] Finished hyperparemeter search!

[I 2023-08-10 12:41:07,337] Searching the best hyperparameters using 4895 samples...
[I 2023-08-10 12:43:12,825] Finished hyperparemeter search!

In [8]:
blender_3 = blend_models(estimator_list = [tuned_catboost, gbc, tuned_rf])

final_model = finalize_model(blender_3)